language: python
python:
  - "2.7"
  - "3.4"
  - "3.6"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq liblzo2-dev
install:
  - pip install codecov pytest-cov
  - pip install -r requirements.txt
  - python setup.py develop
script: pytest --cov=./
after_success:
  - codecov
