language: python
python:
  - "2.7"
  - "3.4"
  - "3.6"
services:
  - postgresql
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq liblzo2-dev
 - sudo apt-get install -qq post
install:
  - pip install codecov pytest-cov
  - pip install -r requirements.txt
  - python setup.py develop
before_script:
  - psql -c 'create database naminggames;' -U postgres
  - psql -c "create user naminggames with password 'naminggames';" -U postgres
script: pytest --cov=./
after_success:
  - codecov
